// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4oeyIyZ3YNnNR-VDCIMZSZ4L8bcQixdU',
    appId: '1:897423988557:web:e48a95289a5498f1fcc904',
    messagingSenderId: '897423988557',
    projectId: 'all-in-all-professional',
    authDomain: 'all-in-all-professional.firebaseapp.com',
    databaseURL: 'https://all-in-all-professional-default-rtdb.firebaseio.com',
    storageBucket: 'all-in-all-professional.appspot.com',
    measurementId: 'G-XQPVDWQCD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOw7rhrm-mudJLKj3IFY0c3NCdCafCWso',
    appId: '1:897423988557:android:90a82034d24b442cfcc904',
    messagingSenderId: '897423988557',
    projectId: 'all-in-all-professional',
    databaseURL: 'https://all-in-all-professional-default-rtdb.firebaseio.com',
    storageBucket: 'all-in-all-professional.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOL6DLUZOR3NtwB7ct9sDIC51a7Qkn7_s',
    appId: '1:897423988557:ios:2fef06136e87162bfcc904',
    messagingSenderId: '897423988557',
    projectId: 'all-in-all-professional',
    databaseURL: 'https://all-in-all-professional-default-rtdb.firebaseio.com',
    storageBucket: 'all-in-all-professional.appspot.com',
    androidClientId: '897423988557-8qf7bl247ok3mg0fqrnj89t15nn7u1i2.apps.googleusercontent.com',
    iosClientId: '897423988557-n2jvedidd7efq1bqm19l1d39q61k8mbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.unicapCg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOL6DLUZOR3NtwB7ct9sDIC51a7Qkn7_s',
    appId: '1:897423988557:ios:2fef06136e87162bfcc904',
    messagingSenderId: '897423988557',
    projectId: 'all-in-all-professional',
    databaseURL: 'https://all-in-all-professional-default-rtdb.firebaseio.com',
    storageBucket: 'all-in-all-professional.appspot.com',
    androidClientId: '897423988557-8qf7bl247ok3mg0fqrnj89t15nn7u1i2.apps.googleusercontent.com',
    iosClientId: '897423988557-n2jvedidd7efq1bqm19l1d39q61k8mbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.unicapCg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4oeyIyZ3YNnNR-VDCIMZSZ4L8bcQixdU',
    appId: '1:897423988557:web:2ddf13e12d592fa4fcc904',
    messagingSenderId: '897423988557',
    projectId: 'all-in-all-professional',
    authDomain: 'all-in-all-professional.firebaseapp.com',
    databaseURL: 'https://all-in-all-professional-default-rtdb.firebaseio.com',
    storageBucket: 'all-in-all-professional.appspot.com',
    measurementId: 'G-ZQ5N3YLP6F',
  );
}
